[workspace]
resolver = "2"
members = [
    "crates/ipatool",
    "vendor/ipatool-core",
]
default-members = ["crates/ipatool"]

[workspace.package]
edition = "2021"
license = "MIT"
version = "1.1.1"
authors = ["ipatool-kit contributors"]
repository = "https://github.com/ipatool-kit/ipatool-kit"

[workspace.dependencies]
ipatool-kit = { path = "crates/ipatool", version = "1.1.1" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
sha2 = "0.10"
hmac = "0.12"
pbkdf2 = { version = "0.12", default-features = false, features = ["hmac"] }
aes-gcm = "0.10"
base64 = "0.22"
hex = "0.4"
plist = "1"
ureq = { version = "2", default-features = false, features = ["tls"] }
crossterm = "0.28"
zip = { version = "2", default-features = false, features = ["deflate"] }
ipatool-kit-core = { path = "vendor/ipatool-core", version = "0.2.0" }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "fs", "time"] }
url = "2"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "cookies", "stream"] }
toml = "0.8"
